version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull ghcr.io/pagopa/oneidentity-load-tests image..
      - docker pull ghcr.io/pagopa/oneidentity-load-tests:test/java-heap
      - ASSUME_ROLE_ARN="arn:aws:iam::${account_id}:role/codebuild"
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name AWSCodeBuild)
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "$${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "$${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "$${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
  build:
    commands: |
      docker run -i -v $(pwd)/src:/src \
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
      ghcr.io/pagopa/oneidentity-load-tests:test/java-heap \
      /src/k6browser_lambda.js
  post_build:
    commands:
      - echo Performance test complete
