version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull ghcr.io/pagopa/pdv-load-tests image..
      - docker pull ghcr.io/pagopa/pdv-load-tests:setup-codebuild
      - export AWS_ACCESS_KEY_ID=$(aws sts get-session-token | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(aws sts get-session-token | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(aws sts get-session-token | jq -r .Credentials.SessionToken)
  build:
    commands: |
        docker run -i -v $(pwd)/src:/src \
        -e HOST_NAME=$HOST_NAME \
        -e API_KEY=$API_KEY \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
        ghcr.io/pagopa/pdv-load-tests:setup-codebuild \
        /src/$TEST_SCRIPT
  post_build:
    commands:
      - echo Performance test complete
