version: 0.2

env:
  variables:
    HOST_NAME: api.pdv.pagopa.it
  parameter-store:
    TEST_SCRIPT: /CodeBuild/testscript
    API_KEY: /CodeBuild/apikey

phases:
  pre_build:
    commands:
      - echo Pull ghcr.io/pagopa/pdv-load-tests image..
      - docker pull ghcr.io/pagopa/pdv-load-tests:main
  build:
    commands:
        - docker run -i -v $(pwd)/src:/src -e HOST_NAME=$HOST_NAME -e API_KEY=$API_KEY ghcr.io/pagopa/pdv-load-tests:main run - /src/$TEST_SCRIPT
  post_build:
    commands:
      - echo Performance test complete
