version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull ghcr.io/pagopa/oneidentity-load-tests image..
      - docker pull ghcr.io/pagopa/oneidentity-load-tests:main
      - ASSUME_ROLE_ARN="arn:aws:iam::471112878885:role/service-role/codebuild-oneid-load-test-service-role"
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name AWSCodeBuild)
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_aROLE}" | jq -r '.Credentials.SessionToken')
  build:
    commands: |
      docker run -i -v $(pwd)/src:/src \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
        ghcr.io/pagopa/oneidentity-load-tests:main \
        /src/k6browser_lambda.js
  post_build:
    commands:
      - echo Performance test complete