version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i grafana/k6 run - <./src/04-patch-users.js
  post_build:
    commands:
      - echo Performance test complete
