name: Artillery Load Test
 
on:
  push:
    branches:
      - main
    paths:
      - 'src/artillery.js'
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - warning
 
jobs:
  artillery:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm i -D @playwright/test
          npm i -D @playwright/browser-chromium
          npx playwright install

      - name: Make reports directory
        run: mkdir reports
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run src/artillery.yml --output reports/report-artillery.json
          #working-directory: ./src
        
      - name: Generate HTML report
        run: run report --output reports/report.html reports/report.json
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artillery-report
          path: reports/*