name: K6 Load Tests Create RequestID
on:
  workflow_dispatch:
    inputs:
      script:
        type: choice
        default: 'step1-5_user_oi_idp.js'
        options:
          - step1-5_user_oi_idp.js
          - IdP_keys.js
          - All_IdP.js
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - warning
 
jobs:
  performance-tests:
    runs-on: ubuntu-latest
    env:
      K6_BROWSER_ENABLED: false
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    
      - name: Setup k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1

      - name: Run k6 test
        uses: grafana/run-k6-action@a784f35f3b2bdccde26814c5ad229b118c865a77 # v1
        with:
          path: |
            ./src/${{ inputs.script }}

      - name: Upload Report
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: k6-browser-report-summary
          path: TestSummaryReport.html

   
