name: Playwright Tests Docker
on:
  push:
    branches: ['main']
    paths:
      - 'src/playwright.js'
  workflow_dispatch:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - warning
 
jobs:
  playwright:
    name: 'Playwright Tests Docker'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-noble
      options: --user 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker pull mcr.microsoft.com/playwright:v1.48.1-noble

      - name: Run Playwright tests
        run: docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.48.1-noble /bin/bash node /src/playwright.js